default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: 
  pool: 5

development:
  <<: *default
  database: hyperdrive_api_development

test:
  <<: *default
  database: hyperdrive_api_test

# production:
#   <<: *default
#   database: hyperdrive_api_production
#   username: hyperdrive_api
#   password: <%= ENV['HYPERDRIVE_API_DATABASE_PASSWORD'] %>
